sudo: false

notifications:
  email: false

language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

# Make chrome browser available for testing
services:
  - xvfb

install:
  - npm install

addons:
  sauce_connect: true

script:
  - COVERAGE=true npm run test
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info;

after_success: sizereport --config
